apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2018-03-23T18:06:19Z
  name: k8s.sspcloudpro.co.in
spec:
  api:
    dns: {}
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://sspucket1/k8s.sspcloudpro.co.in
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.4.4
  masterPublicName: api.k8s.sspcloudpro.co.in
  networkCIDR: 172.31.0.0/16
  networkID: vpc-873abffc
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.192.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
